apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config

data:
  # Key = filename that will appear inside the pod
  # Value = actual content of prometheus.yml
  prometheus.yml: | 
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 8s

    scrape_configs:
      - job_name: 'order_service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['order-service:8000']   # use K8s service name, not localhost

      - job_name: 'user_service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['user-service:8000']    # use K8s service name, not localhost
