apiVersion: apps/v1
kind: Deployment 

metadata:
  name: consul

spec:
  replicas: 3

  selector:             # apps/v1 — must use matchLabels
    matchLabels:
      app: consul

  template:
    metadata:
      labels:
        app: consul

    spec:
      containers:
        - name: consul-container
          image: hashicorp/consul
          ports:
            - containerPort: 8500