apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service

spec:
  replicas: 5

  # to find the pods of this deployment
  selector: 
    matchLabels:
      app: order-service-app
  
  # creating pods of this deployment
  template:
    metadata:
      labels:
        app: order-service-app

    spec:
      containers:
        - name: order-service
          image: order-k8s:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
