apiVersion: v1
kind: Service

metadata:
  name: order-service

spec:
  selector:   # service will only select and send traffic to pods that have a label matching the selector blcok
    app: order-service
  
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  
  type: NodePort 